import './globals.css';
import { Inter } from 'next/font/google';
import { CartProvider } from '@/context/CartContext';
import { UserProvider } from '@/context/UserContext';
import Navbar from '@/components/common/Navbar'; // Import Navbar
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'My E-Commerce App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <CartProvider>
            <Navbar /> {/* Add the Navbar here */}
            {children}
            <Toaster />
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}